version: 0.4
phases:
    install:
      runtime-versions:
        nodejs: 18
      commands:
        - npm install
    build:
        commands:
            - npm run build
artifacts:
  files:
    - package.json
    - "**/*"